package edu.fscj.cen4940.capstone.config;

import edu.fscj.cen4940.capstone.entity.Exercise;
import edu.fscj.cen4940.capstone.entity.Food;
import edu.fscj.cen4940.capstone.enums.ExerciseType;
import edu.fscj.cen4940.capstone.enums.MeasurementUnit;
import edu.fscj.cen4940.capstone.repository.ExerciseRepository;
import edu.fscj.cen4940.capstone.repository.FoodRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DataSeeder {

    private final FoodRepository foodRepository;
    private final ExerciseRepository exerciseRepository;

    public DataSeeder(FoodRepository foodRepository,
                      ExerciseRepository exerciseRepository) {
        this.foodRepository = foodRepository;
        this.exerciseRepository = exerciseRepository;
    }

    @PostConstruct
    public void seedData() {
        seedFoods();
        seedExercises();
    }

    public void seedFoods() {
        if (foodRepository.count() == 0) {
            foodRepository.saveAll(List.of(
                new Food("Cheddar Cheese", 113.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Peanut Butter", 166.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Dark Chocolate (70%)", 155.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Turkey Breast (deli)", 30.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Trail Mix", 137.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Bacon (cooked)", 151.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Cashews", 157.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Walnuts", 185.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Sunflower Seeds", 165.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Beef Jerky", 116.0, 1.0,
                        MeasurementUnit.OUNCE_WEIGHT, 1.0),
                new Food("Pork Chops (raw)", 880.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Tilapia (raw)", 450.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Ground Turkey (raw)", 640.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Mixed Nuts", 2600.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Chicken Thighs (raw)", 980.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Sausage (pork)", 1350.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Lamb (roasted)", 1120.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Duck (roasted)", 1420.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Venison (grilled)", 960.0, 1.0,
                        MeasurementUnit.POUND, 1.0),
                new Food("Chicken Breast (raw, skinless)", 165.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Rice (white, cooked)", 130.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Apple (raw, sliced)", 52.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Broccoli (steamed)", 35.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Almonds", 579.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Oats (dry)", 389.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Salmon (raw)", 208.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Spinach (raw)", 23.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Avocado (raw)", 160.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Sweet Potato (cooked)", 86.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Blueberries (fresh)", 57.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Carrots (raw, chopped)", 41.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Eggs (boiled)", 155.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Pasta (cooked)", 131.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Shrimp (boiled)", 99.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Cucumber (raw, peeled)", 15.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Cherries (sweet, raw)", 63.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Mango (raw)", 60.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Cauliflower (steamed)", 25.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Zucchini (grilled)", 17.0, 100.0,
                        MeasurementUnit.GRAM, 1.0),
                new Food("Bananas", 890.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Potatoes (raw)", 770.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Ground Beef (85% lean)", 2500.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Tofu (firm)", 760.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Turkey (roasted)", 1350.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Ham (baked, lean)", 1450.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("White Bread", 2660.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Cottage Cheese (low-fat)", 980.0, 1.0,
                        MeasurementUnit.KILOGRAM, 1.0),
                new Food("Coconut Water", 19.0, 1.0,
                    MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Energy Drink", 10.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Lemonade", 12.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Chocolate Milk", 15.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Green Tea (unsweetened)", 0.5, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Orange Soda", 13.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Black Coffee (sweetened)", 5.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Apple Juice", 14.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Milkshake (vanilla)", 70.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Vegetable Smoothie", 25.0, 1.0,
                        MeasurementUnit.OUNCE_VOL, 1.0),
                new Food("Cocoa Powder (unsweetened)", 12.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Garlic Powder", 10.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Cinnamon (ground)", 6.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Baking Powder", 2.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Chili Powder", 8.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Olive Oil", 40.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Honey", 21.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Granulated Sugar", 16.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Salt (table)", 0.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Vanilla Extract", 12.0, 1.0,
                        MeasurementUnit.TEASPOON, 1.0),
                new Food("Butter (melted)", 102.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Maple Syrup", 52.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Soy Sauce", 10.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Ketchup", 15.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Mayonnaise", 94.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Salsa", 5.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Ranch Dressing", 73.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Peanut Oil", 120.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Pesto Sauce", 80.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Barbecue Sauce", 29.0, 1.0,
                        MeasurementUnit.TABLESPOON, 1.0),
                new Food("Oatmeal (cooked)", 154.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Quinoa (cooked)", 222.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Greek Yogurt (plain, low-fat)", 100.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Ice Cream (vanilla)", 270.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Cornflakes", 100.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Brown Rice (cooked)", 215.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Peas (cooked)", 117.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Mashed Potatoes (with milk)", 214.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Chili (with beans)", 250.0, 1.0,
                        MeasurementUnit.CUP, 1.0),
                new Food("Orange Juice", 45.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Whole Milk", 61.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Almond Milk (unsweetened)", 15.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Coffee (black)", 1.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Protein Shake (ready-to-drink)", 60.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Coconut Milk", 200.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Tomato Juice", 17.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Soy Milk", 45.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Vegetable Broth", 5.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Chocolate Syrup", 65.0, 100.0,
                        MeasurementUnit.MILLILITER, 1.0),
                new Food("Water", 0.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Soda (cola)", 420.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Beer (lager)", 430.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Wine (red)", 850.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Fruit Smoothie (mixed)", 600.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Iced Coffee (sweetened)", 400.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Sports Drink", 250.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Iced Tea (sweetened)", 370.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Smoothie (protein, berry)", 480.0, 1.0,
                        MeasurementUnit.LITER, 1.0),
                new Food("Kombucha", 150.0, 1.0,
                        MeasurementUnit.LITER, 1.0)
            ));

            System.out.println("Seeded food records.");
        } else {
            System.out.println("Food table already contains data; skipping seed.");
        }
    }

    private void seedExercises() {
        if (exerciseRepository.count() == 0) {
            exerciseRepository.saveAll(List.of(
                    new Exercise(ExerciseType.AEROBIC, "Running"),
                    new Exercise(ExerciseType.AEROBIC, "Cycling"),
                    new Exercise(ExerciseType.AEROBIC, "Swimming"),
                    new Exercise(ExerciseType.AEROBIC, "Jump Rope"),
                    new Exercise(ExerciseType.AEROBIC, "Rowing"),
                    new Exercise(ExerciseType.AEROBIC, "Hiking"),
                    new Exercise(ExerciseType.AEROBIC, "Elliptical"),
                    new Exercise(ExerciseType.AEROBIC, "Stair Climber"),
                    new Exercise(ExerciseType.AEROBIC, "Dancing"),
                    new Exercise(ExerciseType.AEROBIC, "Sprinting"),
                    new Exercise(ExerciseType.ANAEROBIC, "Squats"),
                    new Exercise(ExerciseType.ANAEROBIC, "Deadlift"),
                    new Exercise(ExerciseType.ANAEROBIC, "Bench Press"),
                    new Exercise(ExerciseType.ANAEROBIC, "Bicep Curls"),
                    new Exercise(ExerciseType.ANAEROBIC, "Tricep Dips"),
                    new Exercise(ExerciseType.ANAEROBIC, "Leg Press"),
                    new Exercise(ExerciseType.ANAEROBIC, "Pull-Ups"),
                    new Exercise(ExerciseType.ANAEROBIC, "Push-Ups"),
                    new Exercise(ExerciseType.ANAEROBIC, "Lunges"),
                    new Exercise(ExerciseType.ANAEROBIC, "Shoulder Press"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Yoga"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Pilates"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Toe Touches"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Hamstring Stretch"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Quadriceps Stretch"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Chest Stretch"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Shoulder Stretch"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Side Bend"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Cobra Pose"),
                    new Exercise(ExerciseType.FLEXIBILITY, "Cat-Cow Stretch"),
                    new Exercise(ExerciseType.BALANCE, "Single-Leg Stand"),
                    new Exercise(ExerciseType.BALANCE, "Heel-to-Toe Walk"),
                    new Exercise(ExerciseType.BALANCE, "Bosu Ball Balance"),
                    new Exercise(ExerciseType.BALANCE, "Tai Chi"),
                    new Exercise(ExerciseType.BALANCE, "Standing March"),
                    new Exercise(ExerciseType.BALANCE, "Tree Pose"),
                    new Exercise(ExerciseType.BALANCE, "Side Leg Raise"),
                    new Exercise(ExerciseType.BALANCE, "Balance Board"),
                    new Exercise(ExerciseType.BALANCE, "Hip Circles"),
                    new Exercise(ExerciseType.BALANCE, "Lunge with Reach"),
                    new Exercise(ExerciseType.MIXED, "CrossFit"),
                    new Exercise(ExerciseType.MIXED, "Bootcamp Workout"),
                    new Exercise(ExerciseType.MIXED, "Circuit Training"),
                    new Exercise(ExerciseType.MIXED, "Bodyweight HIIT"),
                    new Exercise(ExerciseType.MIXED, "Functional Training"),
                    new Exercise(ExerciseType.MIXED, "Kickboxing"),
                    new Exercise(ExerciseType.MIXED, "Tabata"),
                    new Exercise(ExerciseType.MIXED, "Rowing Circuit"),
                    new Exercise(ExerciseType.MIXED, "Swimming Intervals"),
                    new Exercise(ExerciseType.MIXED, "Stair Interval Training")
            ));
            System.out.println("Seeded exercise records.");
        } else {
            System.out.println("Exercise table already contains data; skipping seed.");
        }
    }
}